SWP\Component\Seo\Model\SeoMetadata:
  exclusion_policy: ALL
  properties:
    metaTitle:
      expose: true
      groups: [api, api_seo_metadata]
      type: string
    metaDescription:
      expose: true
      groups: [api, api_seo_metadata]
      type: string
    ogTitle:
      expose: true
      groups: [api, api_seo_metadata]
      type: string
    ogDescription:
      expose: true
      groups: [api, api_seo_metadata]
      type: string
    twitterTitle:
      expose: true
      groups: [api, api_seo_metadata]
      type: string
    twitterDescription:
      expose: true
      groups: [api, api_seo_metadata]
      type: string
